-- 002_accommodation.sql
CREATE TABLE room_types (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(255) NULL,
  base_rate DECIMAL(12,2) NOT NULL DEFAULT 0,
  max_guests INT NOT NULL DEFAULT 2,
  amenities_json JSON NULL,
  image_url VARCHAR(255) NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_rt_branch (branch_id),
  CONSTRAINT fk_rt_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE rooms (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  room_type_id BIGINT UNSIGNED NOT NULL,
  room_number VARCHAR(30) NOT NULL,
  floor VARCHAR(20) NULL,
  status ENUM('AVAILABLE','OCCUPIED','CLEANING','MAINTENANCE','RESERVED') NOT NULL DEFAULT 'AVAILABLE',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_rooms (branch_id, room_number),
  INDEX idx_rooms_status (branch_id, status),
  CONSTRAINT fk_rooms_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_rooms_type FOREIGN KEY (room_type_id) REFERENCES room_types(id) ON DELETE RESTRICT
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE guests (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  first_name VARCHAR(80) NOT NULL,
  last_name VARCHAR(80) NOT NULL,
  id_type VARCHAR(40) NULL,
  id_number VARCHAR(60) NULL,
  phone VARCHAR(40) NULL,
  email VARCHAR(160) NULL,
  address VARCHAR(255) NULL,
  nationality VARCHAR(80) NULL,
  vip BOOLEAN NOT NULL DEFAULT FALSE,
  notes TEXT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_guests_branch (branch_id),
  INDEX idx_guests_email (email),
  CONSTRAINT fk_guests_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE reservations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  guest_id BIGINT UNSIGNED NOT NULL,
  room_id BIGINT UNSIGNED NULL,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  adults INT NOT NULL DEFAULT 1,
  children INT NOT NULL DEFAULT 0,
  status ENUM('PENDING','CONFIRMED','CHECKED_IN','CHECKED_OUT','NO_SHOW','CANCELLED') NOT NULL DEFAULT 'PENDING',
  source VARCHAR(40) NULL,
  deposit_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  deposit_method VARCHAR(40) NULL,
  special_requests TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_res_branch_status (branch_id, status),
  INDEX idx_res_dates (check_in_date, check_out_date),
  CONSTRAINT fk_res_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_res_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE RESTRICT,
  CONSTRAINT fk_res_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL,
  CONSTRAINT fk_res_createdby FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE checkins (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  reservation_id BIGINT UNSIGNED NULL,
  guest_id BIGINT UNSIGNED NOT NULL,
  room_id BIGINT UNSIGNED NOT NULL,
  check_in_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expected_check_out_at TIMESTAMP NULL,
  status ENUM('ACTIVE','CHECKED_OUT') NOT NULL DEFAULT 'ACTIVE',
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ci_room (room_id, status),
  CONSTRAINT fk_ci_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE SET NULL,
  CONSTRAINT fk_ci_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ci_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ci_createdby FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE checkouts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  checkin_id BIGINT UNSIGNED NOT NULL,
  check_out_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  room_charges DECIMAL(12,2) NOT NULL DEFAULT 0,
  additional_charges DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  status ENUM('OPEN','PAID','PARTIAL','VOID') NOT NULL DEFAULT 'OPEN',
  cashier_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_co_checkin (checkin_id),
  CONSTRAINT fk_co_checkin FOREIGN KEY (checkin_id) REFERENCES checkins(id) ON DELETE CASCADE,
  CONSTRAINT fk_co_cashier FOREIGN KEY (cashier_id) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE room_transactions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  checkin_id BIGINT UNSIGNED NULL,
  description VARCHAR(255) NOT NULL,
  type ENUM('ROOM_CHARGE','EXTRA_CHARGE','SERVICE','PAYMENT','ADJUSTMENT','REFUND') NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method VARCHAR(40) NULL,
  reference VARCHAR(120) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_rt_branch (branch_id, created_at),
  INDEX idx_rt_checkin (checkin_id),
  CONSTRAINT fk_frx_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_frx_checkin FOREIGN KEY (checkin_id) REFERENCES checkins(id) ON DELETE CASCADE,
  CONSTRAINT fk_frx_createdby FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE availability_calendar (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  room_id BIGINT UNSIGNED NOT NULL,
  date DATE NOT NULL,
  status ENUM('AVAILABLE','RESERVED','OCCUPIED','BLOCKED') NOT NULL DEFAULT 'AVAILABLE',
  reservation_id BIGINT UNSIGNED NULL,
  UNIQUE KEY uq_avail (room_id, date),
  CONSTRAINT fk_avail_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
  CONSTRAINT fk_avail_res FOREIGN KEY (reservation_id) REFERENCES reservations(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;
