-- 003_pos.sql
CREATE TABLE categories (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  parent_id BIGINT UNSIGNED NULL,
  name VARCHAR(120) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_cat_branch (branch_id),
  CONSTRAINT fk_cat_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_cat_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE products (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(160) NOT NULL,
  sku VARCHAR(60) NOT NULL,
  description VARCHAR(255) NULL,
  price DECIMAL(12,2) NOT NULL DEFAULT 0,
  cost DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
  image_url VARCHAR(255) NULL,
  kitchen_station VARCHAR(60) NULL,
  is_available BOOLEAN NOT NULL DEFAULT TRUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_prod_sku (branch_id, sku),
  INDEX idx_prod_cat (branch_id, category_id),
  CONSTRAINT fk_prod_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_prod_cat FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE tables (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(60) NOT NULL,
  capacity INT NOT NULL DEFAULT 4,
  location VARCHAR(80) NULL,
  status ENUM('AVAILABLE','OCCUPIED','RESERVED','CLEANING') NOT NULL DEFAULT 'AVAILABLE',
  qr_code VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_tables_status (branch_id, status),
  CONSTRAINT fk_tables_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE orders (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  table_id BIGINT UNSIGNED NULL,
  guest_id BIGINT UNSIGNED NULL,
  room_id BIGINT UNSIGNED NULL,
  order_type ENUM('DINE_IN','TAKEAWAY','ROOM_SERVICE','ONLINE') NOT NULL DEFAULT 'DINE_IN',
  source ENUM('POS','UBER_EATS','PICKME','WHATSAPP','PHONE') NOT NULL DEFAULT 'POS',
  external_order_id VARCHAR(120) NULL,
  status ENUM('OPEN','SUBMITTED','KOT_SENT','PREPARING','READY','SERVED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'OPEN',
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax DECIMAL(12,2) NOT NULL DEFAULT 0,
  grand_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_status ENUM('UNPAID','PARTIAL','PAID') NOT NULL DEFAULT 'UNPAID',
  created_by BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_orders_branch (branch_id, status, created_at),
  INDEX idx_orders_source (source, external_order_id),
  CONSTRAINT fk_orders_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_orders_table FOREIGN KEY (table_id) REFERENCES tables(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL,
  CONSTRAINT fk_orders_createdby FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE order_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  qty DECIMAL(8,2) NOT NULL DEFAULT 1,
  unit_price DECIMAL(12,2) NOT NULL,
  line_total DECIMAL(12,2) NOT NULL,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes VARCHAR(255) NULL,
  status ENUM('PENDING','KOT_SENT','PREPARING','READY','SERVED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_oi_order (order_id),
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_oi_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE kot_orders (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  kot_number INT NOT NULL,
  kitchen_station VARCHAR(60) NULL,
  status ENUM('SENT','PREPARING','READY','SERVED','CANCELLED') NOT NULL DEFAULT 'SENT',
  printed_at TIMESTAMP NULL,
  prepared_by BIGINT UNSIGNED NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_kot_order (order_id, status),
  CONSTRAINT fk_kot_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_kot_prep FOREIGN KEY (prepared_by) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE kot_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  kot_id BIGINT UNSIGNED NOT NULL,
  order_item_id BIGINT UNSIGNED NOT NULL,
  qty DECIMAL(8,2) NOT NULL DEFAULT 1,
  CONSTRAINT fk_ki_kot FOREIGN KEY (kot_id) REFERENCES kot_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_ki_item FOREIGN KEY (order_item_id) REFERENCES order_items(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE payments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method ENUM('CASH','CARD','QR','BANK_TRANSFER','ONLINE') NOT NULL,
  reference VARCHAR(120) NULL,
  order_id BIGINT UNSIGNED NULL,
  checkin_id BIGINT UNSIGNED NULL,
  event_id BIGINT UNSIGNED NULL,
  status ENUM('PENDING','COMPLETED','FAILED','REFUNDED') NOT NULL DEFAULT 'COMPLETED',
  received_by BIGINT UNSIGNED NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_pay_branch (branch_id, received_at),
  INDEX idx_pay_order (order_id),
  INDEX idx_pay_checkin (checkin_id),
  CONSTRAINT fk_pay_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_pay_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  CONSTRAINT fk_pay_checkin FOREIGN KEY (checkin_id) REFERENCES checkins(id) ON DELETE SET NULL,
  CONSTRAINT fk_pay_receivedby FOREIGN KEY (received_by) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE deliveries (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  driver_name VARCHAR(120) NULL,
  phone VARCHAR(40) NULL,
  status ENUM('ASSIGNED','OUT_FOR_DELIVERY','DELIVERED','FAILED') NOT NULL DEFAULT 'ASSIGNED',
  delivered_at TIMESTAMP NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_del_order (order_id),
  CONSTRAINT fk_del_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;
