-- 004_catering.sql
CREATE TABLE event_packages (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(160) NOT NULL,
  description VARCHAR(255) NULL,
  price_per_guest DECIMAL(12,2) NOT NULL DEFAULT 0,
  min_guests INT NOT NULL DEFAULT 0,
  includes_json JSON NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_epkg_branch (branch_id),
  CONSTRAINT fk_epkg_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE events (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  guest_id BIGINT UNSIGNED NOT NULL,
  event_type ENUM('OUTDOOR','CORPORATE','WEDDING','FUNCTION') NOT NULL,
  name VARCHAR(160) NOT NULL,
  event_date DATE NOT NULL,
  venue VARCHAR(160) NULL,
  no_of_guests INT NOT NULL DEFAULT 0,
  package_id BIGINT UNSIGNED NULL,
  status ENUM('QUOTED','CONFIRMED','ONGOING','COMPLETED','CANCELLED') NOT NULL DEFAULT 'QUOTED',
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  deposit DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_events (branch_id, status, event_date),
  CONSTRAINT fk_events_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_events_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE RESTRICT,
  CONSTRAINT fk_events_pkg FOREIGN KEY (package_id) REFERENCES event_packages(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE quotations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  guest_id BIGINT UNSIGNED NOT NULL,
  event_type ENUM('OUTDOOR','CORPORATE','WEDDING','FUNCTION') NOT NULL,
  event_date DATE NOT NULL,
  guests INT NOT NULL DEFAULT 0,
  line_items_json JSON NULL,
  subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax DECIMAL(12,2) NOT NULL DEFAULT 0,
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  total DECIMAL(12,2) NOT NULL DEFAULT 0,
  valid_until DATE NULL,
  status ENUM('DRAFT','SENT','ACCEPTED','REJECTED','EXPIRED') NOT NULL DEFAULT 'DRAFT',
  converted_event_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_quot_branch (branch_id, status),
  CONSTRAINT fk_quot_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_quot_guest FOREIGN KEY (guest_id) REFERENCES guests(id) ON DELETE RESTRICT,
  CONSTRAINT fk_quot_event FOREIGN KEY (converted_event_id) REFERENCES events(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE event_payments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  event_id BIGINT UNSIGNED NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method ENUM('CASH','CARD','QR','BANK_TRANSFER','ONLINE') NOT NULL,
  reference VARCHAR(120) NULL,
  paid_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  notes TEXT NULL,
  INDEX idx_epay_event (event_id),
  CONSTRAINT fk_epay_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;
