-- 007_finance.sql
CREATE TABLE expense_categories (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(120) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE expenses (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  vendor_name VARCHAR(160) NULL,
  amount DECIMAL(12,2) NOT NULL,
  paid_at DATE NOT NULL,
  payment_method VARCHAR(40) NULL,
  reference VARCHAR(120) NULL,
  description VARCHAR(255) NULL,
  receipt_url VARCHAR(255) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_exp_branch (branch_id, paid_at),
  CONSTRAINT fk_exp_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_exp_cat FOREIGN KEY (category_id) REFERENCES expense_categories(id) ON DELETE RESTRICT,
  CONSTRAINT fk_exp_createdby FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE cash_reconciliations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  reconciliation_date DATE NOT NULL,
  expected_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
  counted_cash DECIMAL(12,2) NOT NULL DEFAULT 0,
  variance DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  status ENUM('DRAFT','APPROVED','DISCREPANCY') NOT NULL DEFAULT 'DRAFT',
  counted_by BIGINT UNSIGNED NULL,
  approved_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_cr_branch (branch_id, reconciliation_date),
  CONSTRAINT fk_cr_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_cr_countedby FOREIGN KEY (counted_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_cr_approvedby FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE bank_transactions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  transaction_date DATE NOT NULL,
  type ENUM('DEPOSIT','WITHDRAWAL','TRANSFER') NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  method VARCHAR(40) NULL,
  reference VARCHAR(120) NULL,
  is_reconciled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_bt_branch (branch_id, transaction_date),
  CONSTRAINT fk_bt_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE
) DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE bank_reconciliations (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  branch_id BIGINT UNSIGNED NOT NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  opening_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_deposits DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_withdrawals DECIMAL(12,2) NOT NULL DEFAULT 0,
  closing_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  status ENUM('DRAFT','RECONCILED') NOT NULL DEFAULT 'DRAFT',
  reconciled_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_br_period (branch_id, period_start, period_end),
  CONSTRAINT fk_br_branch FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE CASCADE,
  CONSTRAINT fk_br_reconciledby FOREIGN KEY (reconciled_by) REFERENCES users(id) ON DELETE SET NULL
) DEFAULT CHARACTER SET utf8mb4;
